version: "3.8"

services:
  solocloud:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solocloud-app
    image: solocloud:latest
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      # 核心配置
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG:-false}
      
      # 数据库配置
      - DATABASE_URL=${DATABASE_URL:-sqlite:////app/data/SoloCloud.db}
      
      # 存储配置
      - STORAGE_PROVIDER=${STORAGE_PROVIDER:-local}
      - UPLOAD_FOLDER=${UPLOAD_FOLDER:-/app/uploads}
      
      # 云存储配置（可选）
      - ALIYUN_OSS_ACCESS_KEY_ID=${ALIYUN_OSS_ACCESS_KEY_ID:-}
      - ALIYUN_OSS_ACCESS_KEY_SECRET=${ALIYUN_OSS_ACCESS_KEY_SECRET:-}
      - ALIYUN_OSS_ENDPOINT=${ALIYUN_OSS_ENDPOINT:-}
      - ALIYUN_OSS_BUCKET_NAME=${ALIYUN_OSS_BUCKET_NAME:-}
      
      # 日志配置
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=${LOG_FILE:-/app/logs/SoloCloud.log}
    volumes:
      # 数据持久化 - 可自定义路径
      - ${DATA_PATH:-./data}:/app/data
      - ${UPLOADS_PATH:-./uploads}:/app/uploads
      - ${LOGS_PATH:-./logs}:/app/logs
      
      # 配置文件挂载（可选）
      - ${CONFIG_PATH:-./config.py}:/app/config.py:ro
    networks:
      - solocloud-network
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "${LOG_MAX_SIZE:-10m}"
        max-file: "${LOG_MAX_FILES:-3}"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: "${CPU_LIMIT:-2}"
          memory: "${MEMORY_LIMIT:-2G}"
        reservations:
          cpus: "${CPU_RESERVATION:-0.5}"
          memory: "${MEMORY_RESERVATION:-512M}"

  nginx:
    image: nginx:alpine
    container_name: solocloud-nginx
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${SSL_PATH:-./ssl}:/etc/nginx/ssl:ro
      - ${NGINX_LOGS_PATH:-./logs/nginx}:/var/log/nginx
    depends_on:
      - solocloud
    networks:
      - solocloud-network
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "${LOG_MAX_SIZE:-10m}"
        max-file: "${LOG_MAX_FILES:-3}"
    deploy:
      resources:
        limits:
          cpus: "${NGINX_CPU_LIMIT:-1}"
          memory: "${NGINX_MEMORY_LIMIT:-512M}"

networks:
  solocloud-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# 可选：定义命名卷（推荐用于生产环境）
volumes:
  solocloud-data:
    driver: local
  solocloud-uploads:
    driver: local
  solocloud-logs:
    driver: local